#include "Port.h"

const Port_ConfigType Port_Configuration= {
	
	PORT_A,PORT_PIN0,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_A,PORT_PIN1,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_A,PORT_PIN2,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_A,PORT_PIN3,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_A,PORT_PIN4,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_A,PORT_PIN5,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_A,PORT_PIN6,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_A,PORT_PIN7,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,

  PORT_B,PORT_PIN0,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_B,PORT_PIN1,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_B,PORT_PIN2,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_B,PORT_PIN3,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_B,PORT_PIN4,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_B,PORT_PIN5,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_B,PORT_PIN6,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_B,PORT_PIN7,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,

	PORT_C,PORT_PIN0,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_C,PORT_PIN1,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_C,PORT_PIN2,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_C,PORT_PIN3,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_C,PORT_PIN4,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_C,PORT_PIN5,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_C,PORT_PIN6,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_C,PORT_PIN7,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,

  PORT_D,PORT_PIN0,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_D,PORT_PIN1,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_D,PORT_PIN2,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_D,PORT_PIN3,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_D,PORT_PIN4,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_D,PORT_PIN5,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_D,PORT_PIN6,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_D,PORT_PIN7,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,

  PORT_E,PORT_PIN0,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_E,PORT_PIN1,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_E,PORT_PIN2,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_E,PORT_PIN3,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_E,PORT_PIN4,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
  PORT_E,PORT_PIN5,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,
 
  PORT_F,PORT_PIN0,PORT_PIN_IN,PULL_DOWN,PORT_PIN_MODE_DIO,   // SW1
  PORT_F,PORT_PIN1,PORT_PIN_OUT,OFF,PORT_PIN_MODE_DIO,        // LED1
  PORT_F,PORT_PIN2,PORT_PIN_OUT,OFF,PORT_PIN_MODE_DIO,        // LED2
  PORT_F,PORT_PIN3,PORT_PIN_OUT,OFF,PORT_PIN_MODE_DIO,        // LED3
  PORT_F,PORT_PIN4,PORT_PIN_IN,PULL_UP,PORT_PIN_MODE_DIO,     // SW2
        
};
        
      

	